name: Deploy teste nestjs heroku and github actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test application
      run: yarn test
      
    - name: deploy to heroky     
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.API_KEY }}
        heroky_app_name: ${{ secrets.APP_NAME}} 
        heroku_email: ${{ secrets.EMAIL}}
        usedocker: true
    
    
